version: '3.1'

services:

  djmongodb:
    image: mongodb/mongodb-community-server:7.0.9-ubuntu2204
    container_name: djmongodb
    hostname: djmongodb
    networks: 
      - djmongonet
#    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME="admin"
      - MONGODB_INITDB_ROOT_PASSWORD="GoatHead"
    volumes:
      - /home/pschneider/djmongodb/data:/data/db:rw

networks:
  djmongonet:
    external: true
