# mongo v5+ requires special CPU support, which I don't have apparently
version: '3.1'

services:

  mongo:
    image: mongo:4.4.26
    container_name: mongodb
    hostname: mongodb
    networks: 
      - mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME="admin"
      - MONGO_INITDB_ROOT_PASSWORD="GoatHead"
#    volumes:
#      - /home/pschneider/mongodb/data:/data/db:rw

networks:
  mongodb:
    external: true
